# Use an official Python runtime as the base image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 8000 to the host
EXPOSE 8000

# Define the command to run the app
CMD ["python", "-m", "http.server", "8000"]
